//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ON_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Shipments = new HashSet<Shipment>();
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int Company_ID { get; set; }
        [Required(ErrorMessage = "Company Name is required.")]
        [MinLength(8, ErrorMessage = "Min 8 Char is Required ")]
        public string Company_Name { get; set; }
        [Required(ErrorMessage = "Address is required.")]
        [MinLength(12,ErrorMessage ="Min 12 Char is Required ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Contact Number is required.")]
        public string Contact_Number { get; set; }
        public Nullable<int> User_ids { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
