//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ON_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Route_ID { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public double Base_Price { get; set; }
        public double Distance { get; set; }
        public Nullable<int> Company_ID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
